#!/usr/bin/env bash

# http://julipedia.meroh.net/2010/01/set-e-and-set-x.html
set -e

# Personal output functions
info () {
  printf "\r\033[00;34m${1}\033[0m\n"
}

warn () {
  printf "\r\033[0;33m${1}\033[0m"
}

doing () {
  printf "\r${1}...\033[s"
}

success () {
  printf "\033[u \033[0;32mOK ${1}\033[0m\n"
}

fail () {
  printf "\033[u \033[0;31mFAIL: ${1}\033[0m\n\n" && exit 1
}


info ""
info "***************************************"
info "***************************************"
info "* @laconbass' dotfiles install script *"
info "***************************************"
info "***************************************"
info ""

DOTFILES=$(pwd)

doing "replacing .bashrc file"\
 && cp "$DOTFILES/.bashrc" ~/.bashrc\
 && source ~/.bashrc\
 && success\
 || fail "sorry, aborting"
